1. Написать функцию выводящую таблицу умножения для заданного пользователем числа

In [ ]:
def table(digit):
  return(str(digit) + "x1 = "+ str(digit*1) + '\n' +
         str(digit) + "x2 = "+ str(digit*2) + '\n' +
         str(digit) + "x3 = "+ str(digit*3) + '\n' +
         str(digit) + "x4 = "+ str(digit*4) + '\n' +
         str(digit) + "x5 = "+ str(digit*5) + '\n' +
         str(digit) + "x6 = "+ str(digit*6) + '\n' +
         str(digit) + "x7 = "+ str(digit*7) + '\n' +
         str(digit) + "x8 = "+ str(digit*8) + '\n' +
         str(digit) + "x9 = "+ str(digit*9) + '\n' +
         str(digit) + "x10 = "+ str(digit*10))

print("Введите число:")
print(table(int(input())))

Введите число:
6
6x1 = 6
6x2 = 12
6x3 = 18
6x4 = 24
6x5 = 30
6x6 = 36
6x7 = 42
6x8 = 48
6x9 = 54
6x10 = 60


2. Напишите функцию, которая будет принимать список чисел и возвращать два числа, абсолютная разность которых минимальна

In [ ]:
def minDiff(lst):
    lst = sorted(lst)
    difference = [lst[i] - lst[i - 1] for i in range(1, len(lst))]
    minIndex = difference.index(min(difference))
    return (lst[minIndex], lst[minIndex + 1])

print("Введите числа через пробел")
print(minDiff(list(map(int, input().split(' ')))))

Введите числа через пробел
27 94 71 53 89 20 48 16
(16, 20)


3. Напишите функцию, которая будет принимать строку и две буквы, после чего осуществлять проверку того, что вторая буква всегда идет после первой

In [ ]:
def stroka(st, letterA, letterB):
  st = st.lower()
  return st.count(letterA) == st.count(letterA + letterB)

print(stroka("Я люблю тебя", 'л', 'ю'))

True


4. Напишите функцию которая находит все числа, на которые делится без остатка введенное пользователем число

In [ ]:
def devisibility(num):
  lst = []
  for i in range(2, num):
    if num%i == 0:
      lst.append(i)
  return(lst)

print(devisibility(int(input())))

586443
[3, 11, 13, 33, 39, 143, 429, 1367, 4101, 15037, 17771, 45111, 53313, 195481]


Написать функцию осуществляющую сложение двух квадратных матриц

In [ ]:
import random
import numpy as np

def sumMatrix(matr1, matr2, size):
  result = np.random.randint(1, size = (size, size))
  for i in range(0, size):
    for j in range (0, size):
      result[i][j] = matr1[i][j] + matr2[i][j]
  return(result)

print("Введите размер матрицы")
size = int(input())
matr1 = np.random.randint(low = -100, high = 100, size = (size, size))
matr2 = np.random.randint(low = -100, high = 100, size = (size, size))

print('\n' + str(matr1) + '\n')
print(str(matr2) + '\n')
print(sumMatrix(matr1, matr2, size))

Введите размер матрицы
4

[[-69 -90 -94  -5]
 [ 89 -42  19  89]
 [ -3  55  10 -48]
 [-73 -90 -95  76]]

[[ 91 -30  -2  19]
 [ 76 -30 -69 -57]
 [ 66  86 -37  12]
 [ 30 -40  92 -15]]

[[  22 -120  -96   14]
 [ 165  -72  -50   32]
 [  63  141  -27  -36]
 [ -43 -130   -3   61]]


6. Написать функцию осуществляющую транспонирование матрицы

In [ ]:
import random
import numpy as np

def sumMatrix(matr, size):
  result = np.random.randint(1, size = (size, size))
  for i in range(0, size):
    for j in range (0, size):
      result[i][j] = matr[j][i]
  return(result)

print("Введите размер матрицы")
size = int(input())
matr = np.random.randint(low = -100, high = 100, size = (size, size))

print('\n' + str(matr) + '\n')
print(sumMatrix(matr, size))

Введите размер матрицы
4

[[ 81 -94 -51 -43]
 [-53 -73  33 -27]
 [ 13  21  19  51]
 [ 53 -59  42  17]]

[[ 81 -53  13  53]
 [-94 -73  21 -59]
 [-51  33  19  42]
 [-43 -27  51  17]]
